server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: 'create'
    show-sql: true
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5433/auth
    username: admin
    password: password